Add Increment A-MoreOOP Refactor the classes into 8 different packages for more MoreOOP
command: contains classes that perform the commands/operations on the TaskList
constant: contains all the magic Constants
duke: contains the main class which is the entry point of the program
exception: contains the exception classes
parser: contains classes that parse the input to give the right command
storage: contains the classes that perform reading and writing to text storage file
task: contains the Task and subclasses and TaskList
ui: contains Printer to print output